--- cargo-crates/wasmtime-0.39.1/Cargo.toml.orig	1970-01-01 00:00:01 UTC
+++ cargo-crates/wasmtime-0.39.1/Cargo.toml
@@ -146,7 +146,6 @@ default = [
     "cranelift",
     "pooling-allocator",
     "memory-init-cow",
-    "vtune",
 ]
 jitdump = ["wasmtime-jit/jitdump"]
 memory-init-cow = ["wasmtime-runtime/memory-init-cow"]
